import { pathToFileURL } from 'node:url';

const API = 'https://api.github.com';
const MAINTAINER = new Set(['OWNER', 'MEMBER', 'COLLABORATOR']);
export const TITLE = 'Maintainer digest';

/** Where a contributor PR stands: green and waiting for us, or waiting for its author. */
export function prState({ checks, lastPushAt, lastMaintainerAt }) {
  if (checks === 'pending') return null;
  if (checks === 'failure') return 'author';
  return lastMaintainerAt && Date.parse(lastMaintainerAt) > Date.parse(lastPushAt) ? 'author' : 'review';
}

/** One short Markdown overview; empty sections say so instead of disappearing. */
export function digest({ date, prs, issues }) {
  const section = (title, rows) => [`### ${title}`, '', ...(rows.length ? rows.map(row => `- #${row.number} ${row.title}${row.by ? ` (@${row.by})` : ''}`) : ['Nothing right now.']), ''];
  return [
    `Week of ${date}. Generated by the weekly digest workflow; the previous digest is closed automatically.`,
    '',
    ...section('Green and waiting for a review', prs.filter(pr => pr.state === 'review')),
    ...section('Waiting for their authors', prs.filter(pr => pr.state === 'author')),
    ...section('New issues without an answer yet', issues.filter(issue => issue.state === 'unanswered')),
    ...section('Waiting for their reporters (needs-info)', issues.filter(issue => issue.state === 'needs-info'))
  ].join('\n');
}

async function github(path, token, init = {}) {
  const response = await fetch(`${API}${path}`, { ...init, headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${token}`,
    'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'chat-on-steroids-weekly-digest', ...(init.headers ?? {}) } });
  if (!response.ok) throw new Error(`GitHub ${path} failed with HTTP ${response.status}`);
  return response.json();
}

async function main() {
  const repository = process.env.GITHUB_REPOSITORY;
  const token = process.env.GH_TOKEN;
  if (!repository || !token) throw new Error('GITHUB_REPOSITORY and GH_TOKEN are required');
  const prs = [];
  for (const pr of await github(`/repos/${repository}/pulls?state=open&per_page=100`, token)) {
    if (pr.draft || MAINTAINER.has(pr.author_association) || pr.user.type === 'Bot') continue;
    const [runs, commits, reviews, comments] = await Promise.all([
      github(`/repos/${repository}/commits/${pr.head.sha}/check-runs?per_page=100`, token),
      github(`/repos/${repository}/pulls/${pr.number}/commits?per_page=100`, token),
      github(`/repos/${repository}/pulls/${pr.number}/reviews?per_page=100`, token),
      github(`/repos/${repository}/issues/${pr.number}/comments?per_page=100`, token)
    ]);
    const checks = runs.check_runs.some(run => run.status !== 'completed') ? 'pending'
      : runs.check_runs.some(run => run.conclusion === 'failure') ? 'failure' : 'success';
    const lastPushAt = commits.at(-1)?.commit.committer.date ?? pr.created_at;
    const maintainerTimes = [...reviews.map(review => ({ at: review.submitted_at, who: review.author_association })),
      ...comments.filter(comment => comment.user.type !== 'Bot').map(comment => ({ at: comment.created_at, who: comment.author_association }))]
      .filter(event => MAINTAINER.has(event.who)).map(event => event.at).sort();
    const state = prState({ checks, lastPushAt, lastMaintainerAt: maintainerTimes.at(-1) });
    if (state) prs.push({ number: pr.number, title: pr.title, by: pr.user.login, state });
  }
  const issues = [];
  const monthAgo = Date.now() - 30 * 86_400_000;
  for (const issue of await github(`/repos/${repository}/issues?state=open&per_page=100`, token)) {
    if (issue.pull_request || issue.title.startsWith(TITLE)) continue;
    if (issue.labels.some(label => label.name === 'needs-info')) { issues.push({ number: issue.number, title: issue.title, state: 'needs-info' }); continue; }
    if (Date.parse(issue.created_at) < monthAgo || MAINTAINER.has(issue.author_association)) continue;
    const comments = issue.comments ? await github(`/repos/${repository}/issues/${issue.number}/comments?per_page=100`, token) : [];
    if (!comments.some(comment => MAINTAINER.has(comment.author_association))) issues.push({ number: issue.number, title: issue.title, by: issue.user.login, state: 'unanswered' });
  }
  const date = new Date().toISOString().slice(0, 10);
  for (const old of await github(`/repos/${repository}/issues?state=open&creator=github-actions%5Bbot%5D&per_page=100`, token)) {
    if (old.title.startsWith(TITLE)) await github(`/repos/${repository}/issues/${old.number}`, token, { method: 'PATCH', body: JSON.stringify({ state: 'closed', state_reason: 'completed' }) });
  }
  await github(`/repos/${repository}/issues`, token, { method: 'POST', body: JSON.stringify({ title: `${TITLE}: week of ${date}`, body: digest({ date, prs, issues }) }) });
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) await main();
